// <auto-generated />
namespace UniProject.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_capacity_course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_capacity_course));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081904349_add_capacity_course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
